name: duse
version: 0.0.1
description: A minimal command-line application.
author: Axel Christ <adracus@gmail.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  restpoint:
    git: git://github.com/Adracus/restpoint.git
  secret_sharing:
    git: git://github.com/duse-io/secret-sharing-dart.git
  rsa: any
  unscripted: ">=0.5.2+1 <0.6.0"
dev_dependencies:
  unittest: any
  mock: any
